name: build and test with matrix

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24, 23, 22]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version}}
          cache: "npm"
      - name: install dependences
        run: npm install
      - name: Run test
        run: npm test

      - name: deploy to render:
        needs: build test
        runs-on: ubuntu-latest
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.API_KEY }}
